root: /Users/daniellerothermel/drotherm
data: ${paths.root}/data
logs: ${paths.root}/logs

my_data: ${paths.data}/${..proj_dir_name}
my_logs: ${paths.logs}/${..proj_dir_name}

run_dir: ${paths.my_logs}/${now:%Y-%m-%d}/${now:%H-%M-%S}
