root: /Users/daniellerothermel/drotherm
proj_dir_name:
data: ${paths.root}/data
logs: ${paths.root}/logs

my_data: ${paths.data}/${paths.proj_dir_name}
my_logs: ${paths.logs}/${paths.proj_dir_name}

run_dir: ${paths.my_logs}/${now:%Y-%m-%d}/${now:%H-%M-%s}
