defaults:
    - paths: mac
    - _self_

paths:
    proj_dir_name: dr_util

hydra:
    run:
        dir: ${paths.run_dir}
    job_logging:
        formatters:
            simple:
                format: "%(asctime)s - %(message)s"
                datefmt: "%Y-%m-%d %H:%M:%S"

metrics:
    loggers:
        - hydra
    init:
        batch_size: list
        num_samples: int
        loss: batch_weighted_avg_list

seed: 42
