defaults:
    - paths: mac
    - s3man_source: refined
    - _self_

paths:
    my_data: ${paths.data}/${s3man_source.out_dir_name}

hydra:
    run:
        dir: ${paths.run_dir}
    job_logging:
        formatters:
            simple:
                format: "%(asctime)s - %(message)s"
                datefmt: "%Y-%m-%d %H:%M:%S"

output:
    file_name: wiki_conf.json
    file: ${paths.my_data}/${output.file_name}
    
proj_dir_name: s3man
